backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: 'static/uploads' # Media files will be stored in the repo under static/images/uploads
public_folder: '/uploads'

collections:
  - label: 'Pages'
    name: 'pages'
    editor:
      preview: false
    files:
      - label: 'Landing Page'
        name: 'landing'
        file: 'src/_settings/landing.json'
        description: 'General Site Settings'
        fields:
          - label: 'Header'
            name: header
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'SubText', name: 'subtext', widget: 'text' }
              - { label: 'Call to Action', name: 'cta', widget: 'string' }
          - label: 'Boxes'
            name: boxes
            widget: 'object'
            fields:
              - { label: 'Box Title', name: 'boxTitle', widget: 'string' }
              - { label: 'Box Subtitle', name: 'boxSubtitle', widget: 'string' }
              - { label: 'Box Item 1 Title', name: 'boxTextTitle1', widget: 'string' }
              - { label: 'Box Item 1', name: 'boxText1', widget: 'string' }
              - { label: 'Box Item 2 Title', name: 'boxTextTitle2', widget: 'string' }
              - { label: 'Box Item 2', name: 'boxText2', widget: 'string' }
              - { label: 'Box Item 3 Title', name: 'boxTextTitle3', widget: 'string' }
              - { label: 'Box Item 3', name: 'boxText3', widget: 'string' }
              - { label: 'Box Item 4 Title', name: 'boxTextTitle4', widget: 'string' }
              - { label: 'Box Item 4', name: 'boxText4', widget: 'string' }
              - { label: 'Box Item 5 Title', name: 'boxTextTitle5', widget: 'string' }
              - { label: 'Box Item 5', name: 'boxText5', widget: 'string' }
              - { label: 'Box Item 6 Title', name: 'boxTextTitle6', widget: 'string' }
              - { label: 'Box Item 6', name: 'boxText6', widget: 'string' }
          - label: 'Flow'
            name: flow
            widget: 'object'
            fields:
              - { label: 'Title', name: 'flowTitle', widget: 'string' }
              - { label: 'SubText', name: 'flowSubtext', widget: 'string' }

      - label: 'Matching Marketplace'
        name: 'matching'
        file: 'src/_settings/matching.json'
        fields:
          - label: 'Header'
            name: matchingheader
            widget: 'object'
            fields:
              - { label: 'Title', name: 'matchingTitle', widget: 'string' }
              - { label: 'SubText', name: 'matchingSubtext', widget: 'text' }

      - label: 'E-Commerce'
        name: 'ecommerce'
        file: 'src/_settings/ecommerce.json'
        fields:
          - label: 'Header'
            name: ecommerceheader
            widget: 'object'
            fields:
              - { label: 'Title', name: 'ecommerceTitle', widget: 'string' }
              - { label: 'SubText', name: 'ecommerceSubtext', widget: 'text' }

      - label: 'Supply Chain Solutions'
        name: 'supplychain'
        file: 'src/_settings/supplychain.json'
        fields:
          - label: 'Header'
            name: supplychainheader
            widget: 'object'
            fields:
              - { label: 'Title', name: 'supplychainTitle', widget: 'string' }
              - { label: 'SubText', name: 'supplychainSubtext', widget: 'text' }

      - label: 'Sourcing Buyers'
        name: 'sourcingbuyers'
        file: 'src/_settings/sourcingbuyers.json'
        fields:
          - label: 'Header'
            name: sourcingbuyersheader
            widget: 'object'
            fields:
              - { label: 'Title', name: 'sourcingbuyersTitle', widget: 'string' }
              - { label: 'SubText', name: 'sourcingbuyersSubtext', widget: 'text' }

      - label: 'Product Buyers'
        name: 'productbuyers'
        file: 'src/_settings/productbuyers.json'
        fields:
          - label: 'Header'
            name: productbuyersheader
            widget: 'object'
            fields:
              - { label: 'Title', name: 'productbuyersTitle', widget: 'string' }
              - { label: 'SubText', name: 'productbuyersSubtext', widget: 'text' }

      - label: 'Garment Makers'
        name: 'garmentmakers'
        file: 'src/_settings/garmentmakers.json'
        fields:
          - label: 'Header'
            name: garmentmakersheader
            widget: 'object'
            fields:
              - { label: 'Title', name: 'garmentmakersTitle', widget: 'string' }
              - { label: 'SubText', name: 'garmentmakersSubtext', widget: 'text' }

      - label: 'Input Suppliers'
        name: 'inputsuppliers'
        file: 'src/_settings/inputsuppliers.json'
        fields:
          - label: 'Header'
            name: inputsuppliersheader
            widget: 'object'
            fields:
              - { label: 'Title', name: 'inputsuppliersTitle', widget: 'string' }
              - { label: 'SubText', name: 'inputsuppliersSubtext', widget: 'text' }

      - label: 'Service Providers'
        name: 'serviceproviders'
        file: 'src/_settings/serviceproviders.json'
        fields:
          - label: 'Header'
            name: serviceprovidersheader
            widget: 'object'
            fields:
              - { label: 'Title', name: 'serviceprovidersTitle', widget: 'string' }
              - { label: 'SubText', name: 'serviceprovidersSubtext', widget: 'text' }

      - label: 'Why Africa'
        name: 'whyafrica'
        file: 'src/_settings/whyafrica.json'
        fields:
          - label: 'Header'
            name: whyafricaheader
            widget: 'object'
            fields:
              - { label: 'Title', name: 'whyafricaTitle', widget: 'string' }
              - { label: 'SubText', name: 'whyafricaSubtext', widget: 'text' }

      - label: 'Plans'
        name: 'plans'
        file: 'src/_settings/plans.json'
        fields:
          - label: 'Header'
            name: plansheader
            widget: 'object'
            fields:
              - { label: 'Title', name: 'plansTitle', widget: 'string' }
              - { label: 'SubText', name: 'plansSubtext', widget: 'text' }

      - label: 'About Us'
        name: 'aboutus'
        file: 'src/_settings/aboutus.json'
        fields:
          - label: 'Header'
            name: aboutusheader
            widget: 'object'
            fields:
              - { label: 'Title', name: 'aboutusTitle', widget: 'string' }
              - { label: 'SubText', name: 'aboutusSubtext', widget: 'text' }

      - label: 'Careers'
        name: 'careers'
        file: 'src/_settings/careers.json'
        fields:
          - label: 'Header'
            name: careersheader
            widget: 'object'
            fields:
              - { label: 'Title', name: 'careersTitle', widget: 'string' }
              - { label: 'SubText', name: 'careersSubtext', widget: 'text' }

      - label: 'Contact Us'
        name: 'contact'
        file: 'src/_settings/contact.json'
        fields:
          - label: 'Header'
            name: contactheader
            widget: 'object'
            fields:
              - { label: 'Title', name: 'contactTitle', widget: 'string' }
              - { label: 'SubText', name: 'contactSubtext', widget: 'text' }

      - label: 'Privacy & Terms'
        name: 'privacy'
        file: 'src/_settings/privacy.json'
        fields:
          - label: 'Header'
            name: privacyheader
            widget: 'object'
            fields:
              - { label: 'Title', name: 'privacyTitle', widget: 'string' }
              - { label: 'SubText', name: 'privacySubtext', widget: 'text' }

      - label: 'Partner'
        name: 'partner'
        file: 'src/_settings/partner.json'
        fields:
          - label: 'Header'
            name: partnerheader
            widget: 'object'
            fields:
              - { label: 'Title', name: 'partnerTitle', widget: 'string' }
              - { label: 'SubText', name: 'partnerSubtext', widget: 'text' }

  - name: 'careers' # Used in routes, e.g., /admin/collections/blog
    label: 'Jobs' # Used in the UI
    folder: '_careers/' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Department',
          name: 'department',
          widget: 'select',
          options: ['Product', 'Growth & Sales', 'Textile & Apparel Design', 'Marketing & Visuals', 'Operations', 'Engineering'],
        }
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Role', name: 'role', widget: 'markdown' }
      - { label: 'Main Tasks', name: 'tasks', widget: 'markdown' }
      - { label: 'What you bring to the table', name: 'table', widget: 'markdown' }
      - { label: 'You will thrive if', name: 'thrive', widget: 'markdown' }
