backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: 'static/uploads' # Media files will be stored in the repo under static/images/uploads
public_folder: '/uploads'

collections:
  - label: 'Pages'
    name: 'pages'
    editor:
      preview: false
    files:
      - label: 'Landing Page'
        name: 'landing'
        file: 'src/_settings/landing.json'
        description: 'General Site Settings'
        fields:
          - label: 'Header'
            name: header
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'SubText', name: 'subtext', widget: 'text' }
              - { label: 'Call to Action', name: 'cta', widget: 'string' }
          - label: 'Boxes'
            name: boxes
            widget: 'object'
            fields:
              - label: 'Header'
                name: header
                widget: 'object'
                fields:
                  - { label: 'Box Title', name: 'title', widget: 'string' }
                  - { label: 'Box Sub Text', name: 'subtext', widget: 'string' }
              - label: 'Boxes'
                name: boxes
                widget: 'object'
                fields:
                  - label: 'Box 1'
                    name: box1
                    widget: 'object'
                    fields:
                      - { label: 'Title', name: 'title', widget: 'string' }
                      - { label: 'Content', name: 'content', widget: 'text' }
                  - label: 'Box 2'
                    name: box2
                    widget: 'object'
                    fields:
                      - { label: 'Title', name: 'title', widget: 'string' }
                      - { label: 'Content', name: 'content', widget: 'text' }
                  - label: 'Box 3'
                    name: box3
                    widget: 'object'
                    fields:
                      - { label: 'Title', name: 'title', widget: 'string' }
                      - { label: 'Content', name: 'content', widget: 'text' }
                  - label: 'Box 4'
                    name: box4
                    widget: 'object'
                    fields:
                      - { label: 'Title', name: 'title', widget: 'string' }
                      - { label: 'Content', name: 'content', widget: 'text' }
                  
          - label: 'Flow'
            name: flow
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Subtitle', name: 'subtext', widget: 'string' }

      - label: 'Matching Marketplace'
        name: 'matching'
        file: 'src/_settings/matching.json'
        fields:
          - label: 'Header'
            name: header
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'SubText', name: 'subtext', widget: 'text' }
          - label: 'Content'
            name: content
            widget: 'object'
            fields:
              - label: 'Database'
                name: database
                widget: 'object'
                fields:
                  - { label: 'Title', name: 'title', widget: 'string' }
                  - { label: 'SubText', name: 'subtext', widget: 'text' }
                  - label: 'Content'
                    name: content
                    widget: 'object'
                    fields:
                      - label: 'For Buyers'
                        name: buyers
                        widget: 'object'
                        fields:
                          - { label: 'Title', name: 'title', widget: 'string' }
                          - { label: 'SubText', name: 'subtext', widget: 'markdown' }
                      - label: 'For Garment Makers'
                        name: gm
                        widget: 'object'
                        fields:
                          - { label: 'Title', name: 'title', widget: 'string' }
                          - { label: 'SubText', name: 'subtext', widget: 'markdown' }
                      - label: 'For Input Suppliers & Service Providers'
                        name: issp
                        widget: 'object'
                        fields:
                          - { label: 'Title', name: 'title', widget: 'string' }
                          - { label: 'SubText', name: 'subtext', widget: 'markdown' }
                      - label: 'Intuitive & Useful Functionalities'
                        name: functionalities
                        widget: 'object'
                        fields:
                          - { label: 'Title', name: 'title', widget: 'string' }
                          - { label: 'SubText', name: 'subtext', widget: 'markdown' }
              - label: 'Marketplace'
                name: marketplace
                widget: 'object'
                fields:
                  - { label: 'Title', name: 'title', widget: 'string' }
                  - { label: 'SubText', name: 'subtext', widget: 'text' }
                  - { label: 'Content', name: 'content', widget: 'markdown' }


      - label: 'E-Commerce'
        name: 'ecommerce'
        file: 'src/_settings/ecommerce.json'
        fields:
          - label: 'Header'
            name: header
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'SubText', name: 'subtext', widget: 'text' }
          - label: 'Content'
            name: content
            widget: 'object'
            fields:
              - label: 'Drops'
                name: drops
                widget: 'object'
                fields:
                  - { label: 'Title', name: 'title', widget: 'string' }
                  - { label: 'Subtext', name: 'subtext', widget: 'text' }
                  - { label: 'Content', name: 'content', widget: 'markdown' }
              - label: 'Fast Custom'
                name: fastcustom
                widget: 'object'
                fields:
                  - { label: 'Title', name: 'title', widget: 'string' }
                  - { label: 'Subtext', name: 'subtext', widget: 'text' }
                  - { label: 'Content', name: 'content', widget: 'markdown' }
              - label: 'Brands'
                name: brands
                widget: 'object'
                fields:
                  - { label: 'Title', name: 'title', widget: 'string' }
                  - { label: 'Subtext', name: 'subtext', widget: 'text' }
                  - { label: 'Content', name: 'content', widget: 'markdown' }

      - label: 'Supply Chain Solutions'
        name: 'supplychain'
        file: 'src/_settings/supplychain.json'
        fields:
          - label: 'Header'
            name: header
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'SubText', name: 'subtext', widget: 'text' }
          - label: 'Content'
            name: content
            widget: 'object'
            fields:
              - label: 'Support Services'
                name: support
                widget: 'object'
                fields:
                  - { label: 'Title', name: 'title', widget: 'string' }
                  - { label: 'Subtext', name: 'subtext', widget: 'text' }
                  - { label: 'Content', name: 'content', widget: 'markdown' }
              - label: 'Virtual Supplier'
                name: virtual
                widget: 'object'
                fields:
                  - { label: 'Title', name: 'title', widget: 'string' }
                  - { label: 'Subtext', name: 'subtext', widget: 'text' }
                  - { label: 'Content', name: 'content', widget: 'markdown' }
              - label: 'Advisory'
                name: advisory
                widget: 'object'
                fields:
                  - { label: 'Title', name: 'title', widget: 'string' }
                  - { label: 'Subtext', name: 'subtext', widget: 'text' }
                  - { label: 'Content', name: 'content', widget: 'markdown' }
              - label: 'Online Order Tracking'
                name: onlinetracking
                widget: 'object'
                fields:
                  - { label: 'Title', name: 'title', widget: 'string' }
                  - { label: 'Subtext', name: 'subtext', widget: 'text' }
                  - { label: 'Content', name: 'content', widget: 'markdown' }
              - label: 'Corporate Discount'
                name: discounts
                widget: 'object'
                fields:
                  - { label: 'Title', name: 'title', widget: 'string' }
                  - { label: 'Subtext', name: 'subtext', widget: 'text' }
                  - { label: 'Content', name: 'content', widget: 'markdown' }

      - label: 'Sourcing Buyers'
        name: 'sourcingbuyers'
        file: 'src/_settings/sourcingbuyers.json'
        fields:
          - label: 'Header'
            name: header
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'SubText', name: 'subtext', widget: 'text' }

      - label: 'Product Buyers'
        name: 'productbuyers'
        file: 'src/_settings/productbuyers.json'
        fields:
          - label: 'Header'
            name: header
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'SubText', name: 'subtext', widget: 'text' }

      - label: 'Garment Makers'
        name: 'garmentmakers'
        file: 'src/_settings/garmentmakers.json'
        fields:
          - label: 'Header'
            name: header
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'SubText', name: 'subtext', widget: 'text' }

      - label: 'Input Suppliers'
        name: 'inputsuppliers'
        file: 'src/_settings/inputsuppliers.json'
        fields:
          - label: 'Header'
            name: header
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'SubText', name: 'subtext', widget: 'text' }

      - label: 'Service Providers'
        name: 'serviceproviders'
        file: 'src/_settings/serviceproviders.json'
        fields:
          - label: 'Header'
            name: header
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'SubText', name: 'subtext', widget: 'text' }

      - label: 'Why Africa'
        name: 'whyafrica'
        file: 'src/_settings/whyafrica.json'
        fields:
          - label: 'Header'
            name: header
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'SubText', name: 'subtext', widget: 'text' }

      - label: 'Pricing'
        name: 'pricing'
        file: 'src/_settings/pricing.json'
        fields:
          - label: 'Header'
            name: header
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'SubText', name: 'subtext', widget: 'text' }

      - label: 'About Us'
        name: 'aboutus'
        file: 'src/_settings/aboutus.json'
        fields:
          - label: 'Header'
            name: header
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'SubText', name: 'subtext', widget: 'text' }

      - label: 'Careers'
        name: 'careers'
        file: 'src/_settings/careers.json'
        fields:
          - label: 'Header'
            name: header
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'SubText', name: 'subtext', widget: 'text' }

      - label: 'Sustainability'
        name: 'sustainability'
        file: 'src/_settings/sustainability.json'
        fields:
          - label: 'Header'
            name: header
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'SubText', name: 'subtext', widget: 'text' }

      - label: 'Contact Us'
        name: 'contact'
        file: 'src/_settings/contact.json'
        fields:
          - label: 'Header'
            name: header
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'SubText', name: 'subtext', widget: 'text' }

      - label: 'Privacy & Terms'
        name: 'privacy'
        file: 'src/_settings/privacy.json'
        fields:
          - label: 'Header'
            name: header
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'SubText', name: 'subtext', widget: 'text' }

      - label: 'Partner'
        name: 'partner'
        file: 'src/_settings/partner.json'
        fields:
          - label: 'Header'
            name: header
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'SubText', name: 'subtext', widget: 'text' }

  - name: 'careers' # Used in routes, e.g., /admin/collections/blog
    label: 'Jobs' # Used in the UI
    folder: '_careers/' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Department',
          name: 'department',
          widget: 'select',
          options: ['Product', 'Growth & Sales', 'Textile & Apparel Design', 'Marketing & Visuals', 'Operations', 'Engineering'],
        }
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Role', name: 'role', widget: 'markdown' }
      - { label: 'Main Tasks', name: 'tasks', widget: 'markdown' }
      - { label: 'What you bring to the table', name: 'table', widget: 'markdown' }
      - { label: 'You will thrive if', name: 'thrive', widget: 'markdown' }
